a=input('Digite algo:')
print('O tipo primitivo desse valor "{}" é: {}'.format(a, type(a)))
print('"{}" É um número ? "{}"'.format(a, a.isnumeric()))
print('"{}" É alfabético ? "{}"'.format(a, a.isalpha()))
print('"{}" É alfanúmerico ? "{}"'.format(a, a.isalnum()))
print('"{}" Só tem espaço ? "{}"'.format(a, a.isspace()))
print('"{}" Está em maiúscula ? "{}"'.format(a, a.isupper()))
print('"{}" Está em minuscúlo ? "{}"'.format(a, a.islower()))
print('"{}" Está capitalizado ? "{}"'.format(a, a.istitle()))